# Image base
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /src

# Xác định cổng mà ứng dụng sẽ lắng nghe
EXPOSE 5179

# Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./user.csproj"
RUN dotnet publish "./user.csproj" -c Release -o /app

# Run
FROM base AS final
WORKDIR /src
COPY --from=build /app .
ENTRYPOINT ["dotnet", "user.dll"]
