# Sử dụng image Node.js
FROM node:20

# Tạo thư mục làm việc trong container
WORKDIR /src

COPY . .

# Sao chép file package.json và package-lock.json vào container
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install


# Mở cổng 5000
EXPOSE 5000

# Chạy ứng dụng bằng file gateway.js
CMD ["node", "./src/server.js"]
