CREATE DATABASE UserService
GO

USE UserService
GO

CREATE TABLE ROLE(
	IdRole INT IDENTITY(1,1) PRIMARY KEY,
	NameRole NVARCHAR(100)
)

CREATE TABLE USERS(
	IdUser UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Password NVARCHAR(30) NOT NULL,
	idRole INT NOT NULL DEFAULT(2),
	CONSTRAINT FK_USERS_Role FOREIGN KEY(idRole) REFERENCES ROLE(IdRole)
)

INSERT INTO ROLE VALUES
('ADMIN'),
('CUSTOMER'),
('STAFF'),
('BUSINESS PARTNER')

SELECT * FROM ROLE