CREATE DATABASE UserService
GO

USE UserService
GO

CREATE TABLE ROLE(
	IdRole INT IDENTITY(1,1) PRIMARY KEY,
	NameRole NVARCHAR(100)
)

CREATE TABLE Users(
	IdUser UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Password NVARCHAR(30) NOT NULL,
	NameUser NVARCHAR(100),
	BirthDay DATE,
	CreateAt DATETIME,
	idRole INT NOT NULL DEFAULT(2),
	CONSTRAINT FK_USERS_Role FOREIGN KEY(idRole) REFERENCES ROLE(IdRole)
)

INSERT INTO ROLE VALUES
('ADMIN'),
('CUSTOMER'),
('STAFF'),
('BUSINESS PARTNER')
ALTER TABLE Users
ALTER COLUMN Password NVARCHAR(255);

SELECT * FROM ROLE
SELECT * FROM USERS


/* Create Account To Use Docker */

CREATE LOGIN HuyLieu WITH PASSWORD = 'Giahuy1603';
CREATE USER HuyLieu FOR LOGIN HuyLieu;
EXEC sp_addrolemember 'db_datareader', 'HuyLieu';
EXEC sp_addrolemember 'db_datawriter', 'HuyLieu';

EXEC sp_helplogins 'HuyLieu';

SELECT name FROM sys.databases;
GO


SELECT *
FROM sys.sql_logins
WHERE name = 'sa';

ALTER LOGIN sa ENABLE;

ALTER LOGIN sa WITH PASSWORD = 'Giahuy1603';
